// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd99vxaTZneFbbHKWXOuewlLWKNyXggGU',
    appId: '1:32157259608:web:3deaeabf7e1ebc5cbc772d',
    messagingSenderId: '32157259608',
    projectId: 'kedaikita-42031',
    authDomain: 'kedaikita-42031.firebaseapp.com',
    storageBucket: 'kedaikita-42031.firebasestorage.app',
    measurementId: 'G-7TJEGKLV1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy9jhgZQvBqT43Dh8VTE1ojOuuoQ6VO34',
    appId: '1:32157259608:android:bdfe07216d6972d1bc772d',
    messagingSenderId: '32157259608',
    projectId: 'kedaikita-42031',
    storageBucket: 'kedaikita-42031.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfjsorOkQkR-TenZxDI1ngvK5ZxIlgyMU',
    appId: '1:32157259608:ios:bb48199fc29339adbc772d',
    messagingSenderId: '32157259608',
    projectId: 'kedaikita-42031',
    storageBucket: 'kedaikita-42031.firebasestorage.app',
    iosBundleId: 'com.example.kedaiKita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfjsorOkQkR-TenZxDI1ngvK5ZxIlgyMU',
    appId: '1:32157259608:ios:bb48199fc29339adbc772d',
    messagingSenderId: '32157259608',
    projectId: 'kedaikita-42031',
    storageBucket: 'kedaikita-42031.firebasestorage.app',
    iosBundleId: 'com.example.kedaiKita',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd99vxaTZneFbbHKWXOuewlLWKNyXggGU',
    appId: '1:32157259608:web:2eaddb788e891326bc772d',
    messagingSenderId: '32157259608',
    projectId: 'kedaikita-42031',
    authDomain: 'kedaikita-42031.firebaseapp.com',
    storageBucket: 'kedaikita-42031.firebasestorage.app',
    measurementId: 'G-FRC1YM5Y1N',
  );
}
